name: rx_simplify
description: A starting point for Dart libraries or applications.
version: 0.0.2

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  pedantic: ^1.9.0
  more: 3.0.0-nullsafety.6
  rxdart: 0.26.0-nullsafety.1
  path: 1.8.0-nullsafety.3

dev_dependencies:
  test: ^1.14.4
  analyzer: any
